Background script
CarlosCRG19/sandwich-ai pull request #14
Opened 2024-05-16 22:35 UTC by Int-Angel

Features:
- Action handler complete for click and type actions
- Multiple actions handler
- bacground script
- sync background script with front
- steps status

2024-05-16 23:20 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +    await sleep(4000);
por qué necesitamos este sleep?

2024-05-16 23:29 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +    await sleep(4000);
ya lo quite alv mas adelnate
sabes como puede hacer un stash o algo para que solo se vea lo final mejor?

2024-05-16 23:33 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +    await sleep(4000);
no te creas amiga, se me fue, era para test

2024-05-16 23:34 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +    await sleep(4000);
por qué necesitamos este sleep?

2024-05-16 23:34 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +  });
por qué se ejecuta este script en este punto? para cargar las funciones de ese archivo?

2024-05-16 23:34 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +  for (const step of steps) {
ojo que  el for loop crea una copia de los objetos de `steps` por lo que los cambios que se hagan en esta copia no se verán reflejados en los elementos del array original... esto significa que en la línea 57, donde seteas un estado de error en el `step` (`step.state="failed"`) ese cambio de estado no se va a mandar cuando corres `chrome.runtime.sendMessage` en la linea 58

así está planeado?

2024-05-16 23:34 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +      .then((response) => JSON.parse(response[0].result));
esto no se puede simplificar si `executeAction` recibe `action_response`? y así ya no se necesita el `self`.

```suggestion
    const action_execution_response = await chrome.scripting
      .executeScript({
        target: { tabId: active_tab[0].id },
        // eslint-disable-next-line no-undef -- executeAction is defined in the injected script
        func: () => executeAction({ action_response }),
      })
      .then((response) => JSON.parse(response[0].result));
```

2024-05-16 23:35 UTC, CarlosCRG19 commented on chrome-extension/background/utils/executeActionsScript.js
> +  return JSON.stringify({ status: "sucess" });
```suggestion
  return JSON.stringify({ status: "success" });
```

2024-05-16 23:37 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +  });
simon, metemos todo el file en el tab de una y mas adelante solo llamamos a la funcion para que ejecute las acciones

2024-05-16 23:41 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +  for (const step of steps) {
si se manda de manera correcta los estados de las acciones, creo que tiene que ver con que step es un objeto, pero nose bien como funcione internamente, pero jala

2024-05-16 23:44 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +  });
chido chido

2024-05-16 23:45 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +  for (const step of steps) {
qué raro, juraría que es una copia profunda... pero va, se juega

2024-05-16 23:45 UTC, CarlosCRG19 approved these changes

2024-05-16 23:51 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +      .then((response) => JSON.parse(response[0].result));
yo tampoco queria usar el self jajaj, el problema es que no estamos llamando a la funcion executeAction aqui como tal, estamos injectando una llamada a la funcion y action_response esta en la extension y no en la tab donde inyectamos el codigo.

Y cuando le pasamos parametros como propones, la tab espera que ese parametro este declarado en el contexto de la tab y ps esta undefined y no le llega nada.

hay algunos workarounds pero creo que es el mejor este

2024-05-16 23:52 UTC, CarlosCRG19 commented on chrome-extension/background/utils/processSteps.js
> +      currentView: image,
the API uses snake case. changing this to camel case breaks the call
```suggestion
      current_view: image,
```

2024-05-16 23:53 UTC, Int-Angel commented on chrome-extension/background/utils/executeActionsScript.js
> +  return JSON.stringify({ status: "sucess" });
jiji upsi

2024-05-16 23:53 UTC, CarlosCRG19 requested changes
change `currentView` to `current_view` when calling the API

2024-05-16 23:56 UTC, Int-Angel commented on chrome-extension/background/utils/processSteps.js
> +  for (const step of steps) {
ni idea, no pude encontrar documentacion de eso, pero si jala, testeado y todo

2024-05-17 00:33 UTC, CarlosCRG19 approved these changes

2024-05-17 00:33 UTC, merged